#!/usr/bin/env sh
set -e

. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
NC='\033[0m' # No Color

npm run lint
lint_exit_code=$?

if [ $lint_exit_code -ne 0 ]; then
  echo -e "${RED}ESLint found errors in your code. Please fix them before committing.${NC}"
  exit 1
fi

npm run test || (echo -e "${RED}Ooops! Tests failed. Please make sure all tests are passing before committing.${NC}" && false)
